# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num" #pagination generated sub path format
#pygments: true #for support {% highlight %}
highlighter: pygments
markdown: kramdown #use kramdown to parse markdown
encoding: utf-8

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: "hg0088"

description: "hg0088, share technology post"
author:
  name: hg0088
  email: wwj99cloud@163.com
  github: hg0088	
  twitter: hg0088
  pinterest: asd123
  linkedin: asd123
  bio: Do not build on quicksand high
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: category.html
tags_path: tag.html

BASE_PATH: 
